# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stat_bllcorr_downOrUp <- function(x) {
    .Call('_libGetDataR_stat_bllcorr_downOrUp', PACKAGE = 'libGetDataR', x)
}

