# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title stat_bllcorr_downOrUp: has the price fall or rised compaired to the previous price?
#' @description bellow is a function that gets a numeric vector and return whether the value
#' has down or up compairing with their previous value
#' if the any of the compairing values is NA the value is 0 ( unconsider ), 1 for has up
#' -1 for has down
#' @param x the a NumericVector with the values
#' @return a NumeriVector with the same size that the 'x' parameter with the values:
#' -1 (has fallen), 0 (unconsider), 1 (has raisen).
stat_bllcorr_downOrUp <- function(x) {
    .Call('_libGetDataR_stat_bllcorr_downOrUp', PACKAGE = 'libGetDataR', x)
}

#' @title stat_bllcorr_doesExogPredictsEndog: compaire exog and endog and return a vector of the comparison,
#' should take proprocessed Vectors from the function 'stat_bllcorr_downOrUp'
#' @description the code bellow will do a comparison if the exog was capable to predict the endog
#' @param exog a lagged NumericVector to check whether can predicts endog
#' @param the NumericVector to check whether exog has predicted this
#' @return a NumericVector of the result of the coparison of the same size than input and
#' with values: -1 (oposite direction), 0 (unconsider), 1 (same direction).
stat_bllcorr_doesExogPredictsEndogCateg <- function(exog, endog) {
    .Call('_libGetDataR_stat_bllcorr_doesExogPredictsEndogCateg', PACKAGE = 'libGetDataR', exog, endog)
}

